//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiTodo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public int IdTodo { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string AttachType { get; set; }
        public byte[] AttachFile { get; set; }
    }
}
